#ifndef AXE_STATUS_CODES_HPP
#define AXE_STATUS_CODES_HPP

namespace axe {
enum class StatusCode {
  Continue = 100,
  switchingProtocols,
  processing,
  earlyHints,
  ok = 200,
  created,
  accepted,
  nonAuthoritativeInformation,
  noContent,
  resetContent,
  partialContent,
  multiStatus,
  alreadyReported,
  IMUsed = 226,
  multipleChoices = 300,
  movedPermanently,
  found,
  seeOther,
  notModified,
  useProxy,
  switchProxy,
  temporaryRedirect,
  permanentRedirect,
  badRequest = 400,
  unauthorized,
  paymentRequired,
  forbidden,
  notFound,
  methodNotAllowed,
  notAcceptable,
  proxyAuthenticationRequired,
  requestTimeout,
  conflict,
  gone,
  lengthRequired,
  preconditionFailed,
  payloadTooLarge,
  URITooLarge,
  unsupportedMediaType,
  rangeNotSatisfiable,
  expectationFailed,
  imATeapot,
  misdirectedRequest = 421,
  unprocessableEntity,
  locked,
  failedDependency,
  tooEarly,
  upgradeRequired,
  preconditionRequired = 428,
  tooManyRequests,
  requestHeaderFieldsTooLarge,
  unavailableForLegalReasons,
  internalServerError = 500,
  notImplemented,
  badGateway,
  serviceUnavailable,
  gatewayTimeout,
  httpVersionNotSupported,
  variantAlsoNegotiates,
  insufficientStorage,
  loopDetected,
  notExtended,
  networkAuthenticationRequired,
  _pageExpired = 419,
  _methodFailure,
  _headerFieldsTooLarge = 430,
  _loginTimeout = 440,
  _retryWith = 449,
  _blockedByWindowsParentalControls = 450,
  _redirect = 451,
  _invalidToken = 498,
  _tokenRequired,
  _bandwidthLimitExceeded = 509,
  _siteIsOverloaded = 529,
  _siteIsFrozen,
  _networkReadTimeoutError = 598,
  _networkConnectTimeoutError,
  _noResponse = 444,
  _headerTooLarge = 494,
  _SSLCertificateError,
  _SSLCertificateRequired,
  _HTTPRequestSentToHTTPSPort,
  _clientClosedRequest = 499,
  _webServerReturnedAnUnknownError = 520,
  _webServerIsDown,
  _connectionTimedOut,
  _originIsUnreachable,
  _aTimeoutOccurred,
  _SSLHandshakeFailed,
  _invalidSSLCertificate,
  _railgunError,
  _cloudflare530,
  _closedConnectionBeforeTimeout = 460,
  _manyIPAddressesInXForwardedForHeader = 463,
  _unauthorizedByIdentityProvider = 561,
};
}

#endif AXE_STATUS_CODES_HPP